### ISSUE TITLE
Website interface

### ISSUE THREAD

**Issue by GlitchMasta47** [GlitchMasta47/chrome-extensions#1]
Provide a website for this repository through GitHub pages, and provide each chrome extension with a download button

## Todo
- [ ] Actually create the website
- [ ] Put it live on GitHub pages
- [ ] If an anchor is included in the URL (for example, `https://glitchmasta47.github.io/chrome-extensions#some-extension`) then instead of showing all of the extensions only show the one, expanded and showing the entire readme as well as providing a download button
